variables:
  WERF_VERSION: 1.2 ea

stages:
  - deploy

# Base deployment
.deploy:
  stage: deploy
  script:
    - source ~/.bashrc
    - echo $PATH
    - type multiwerf && source $(multiwerf use ${WERF_VERSION} --as-file)
    - type werf && source $(werf ci-env gitlab --as-file)
    - werf converge
      --namespace ${CI_NAMESPACE}
      --set "global.ci_url=$(cut -d / -f 3 <<< $CI_ENVIRONMENT_URL)"
  tags:
    - werf
# Base deployment CRD
.deployCRD:
  stage: deploy
  script:
    - source ~/.bashrc
    - echo $PATH
    - type multiwerf && source $(multiwerf use ${WERF_VERSION} --as-file)
    - type werf && source $(werf ci-env gitlab --as-file)
    - werf converge
      --namespace ${CI_NAMESPACE}
      --set "global.ci_url=$(cut -d / -f 3 <<< $CI_ENVIRONMENT_URL)"
      --set "CRD.enabled=true"
  tags:
    - werf

Deploy to Dev:
  extends: .deploy
  environment:
    name: dev
    url: http://dev.gs.example.com
  variables:
    CI_NAMESPACE: veverse-gs-dev
  only:
    - branches
  when: manual
  tags:
    - aws
Deploy to Test:
  extends: .deploy
  environment:
    name: test
    url: http://test.gs.example.com
  variables:
    CI_NAMESPACE: veverse-gs-test
  only:
    - branches
  when: manual
  tags:
    - aws
Deploy to Production:
  extends: .deploy
  environment:
    name: prod
    url: http://gs.example.com
  variables:
    CI_NAMESPACE: veverse-gs-prod
  only:
    - tags
  when: manual
  tags:
    - aws
Deploy CRD to Production:
  extends: .deployCRD
  environment:
    name: prod
    url: http://gs.example.com
  variables:
    CI_NAMESPACE: veverse-gs-prod
  only:
    - tags
  when: manual
  tags:
    - aws
