{{- if .Values.CRD.enabled  }}
# CRD
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gameservers.stable.veverse.com
spec:
  group: stable.veverse.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                settings:
                  type: object
                  properties:
                    host:
                      type: string
                    key:
                      type: string
                    maxPlayers:
                      type: integer
                    spaceId:
                      type: string
                    serverId:
                      type: string
                    serverName:
                      type: string
                    apiEmail:
                      type: string
                    apiPassword:
                      type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
  scope: Namespaced
  names:
    plural: gameservers
    singular: gameserver
    kind: GameServer
    shortNames:
      - gs
{{- end }}