---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: veverse-acc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veverse-acc
rules:
  - apiGroups:
      - stable.veverse.com
    resources:
      - gameservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - events
      - configmaps
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "get"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veverse-acc
subjects:
  - kind: ServiceAccount
    name: veverse-acc
    namespace: veverse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veverse-acc
