---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veverse-acc-test
subjects:
  - kind: ServiceAccount
    name: veverse-acc
    namespace: veverse-api-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veverse-acc
